### ISSUE TITLE
Juan Mendez Final Project HangMan

### ISSUE THREAD

**Issue by jmendez50** [valencia-cop1000-201620/final-project#41] opened 2016-04-21 03:30 UTC
### Name
Juan Marcos Mendez

### Proposed Project Description
Well I was think maybe something like hangman. What you would happen is you would be given a word and you would have 6 tries to get it wright.
The words will be selected from a group of words that are in a different file. So you might be able to cheat. Unless i find a way for it to look online for a random word. not sure thought might need help with that.
  ======|
   |         o
   |         /|\
   |         / \
Might look something like that. idk just an idea. not even sure if it's a good one idea.

### Connecting Concepts
Well it will barrow from week 7 file paths and and week 3. Really its something from every week.

### Timing
Well won't take to long. Maybe 2 days depending on when i get out of work this week.

### Asking for...
I don't know what to ask for. If you wanna do my project for me i wont cry about it. lol

**Comment by digitalBeast** [comment] 2016-04-21 04:59
lol the hangman project is a great idea to be honest, I am actually going to do my own hangman project too. Just going to be slightly different. Feel free to ask me advises!

**Comment by halfaro1** [comment] 2016-04-21 12:33
@jmendez50 thanks for the proposal! It looks like hangman is pretty popular (see #31, #42, and #43). So I'll suggest you modify this a little bit and either (a) make a different word game altogether or (b) change the idea of hangman enough so that this game is completely original.

**Comment by jmendez50** [comment] 2016-04-22 04:19
Well its hard to think of something to do. Cant someone just tell me what to do. I'm not good with ideas on the fly. maybe Rock paper scissors with like some kind of twist.

**Comment by halfaro1** [comment] 2016-04-22 20:30
@jmendez50 that's also an idea someone else has come up with, unfortunately. Have you looked through your book? There are a number of unfinished projects at the end of each chapter.

**Comment by elicegreen** [comment] 2016-04-24 04:45
How about maybe creating a wheel of fortune game? 
It's very similar to hang man, same concept of guessing the word.
You can create a list for the wheel options and randomize it as the player "spins the wheel".
Just an idea.

**Comment by halfaro1** [comment] 2016-04-24 14:31
@jmendez50 love the suggestion that @elicegreen gave you

**Comment by jmendez50** [comment] 2016-04-27 00:57
Ok that sounded good. I took the professor's comment as approval to do what elicegreen suggested. Started it

**Comment by halfaro1** [comment] 2016-04-27 12:16
@jmendez50 it's not approved yet. Please post here what you'd like to do for a wheel of fortune game. Good design is core to good programming. What features do you hope your game will have? What Python libraries do you think you'll need? Is your game player v. player or player v. computer? These are just a few questions we need answered.

**Comment by jmendez50** [comment] 2016-04-27 21:35
Name

Juan Marcos Mendez

Proposed Project Description
Wheel of Fortune will be the game and there will be 2 files one where the player can add words. and another to will be the game. The reason for this is so the player cant see what words he/she might get.

Might look something like this.
____________________________________
Welcome to Wheel of Fortune!

Your category is Pets,

===_-_-_-_-_===
Now Spin the Wheel
waits for player input of any key to spin
300
Player inputs L
===L-_-_-_-_-_===
Your score is now 300
Now Spin the Wheel
waits for player input
I
I is a vowel. This will cost you 100.
Y for yes, N for no?
input Y
-100
===L-I-_-_-_-_===
Your score is now 200.
Now Spin the Wheel.
Solve
You would like to Solve?
Y for yes, N for No.
input y
Lizard
===L-I-Z-A-R-D===
You win +10,000
Your Score is 10,200
___________________________________
The game would be something like that.








 
Connecting Concepts

Well it will barrow from week 7 file paths and and week 3. Really its something from every week.

Timing

Well won't take to long. Maybe 2 days depending on when i get out of work this week.

Asking for...

I don't know what to ask for. If you wanna do my project for me i wont cry about it. lol

**Comment by halfaro1** [comment] 2016-04-27 22:09
@jmendez50 in the short time you have, I recommend making a simplified version. 

You'll have to start by designing the wheel. What are all the possible places the wheel can land? How will you model that within Python? I like how the user can spin the wheel, but they should probably have some instructions that tell them to press a key to spin.

Then, move on to designing the letter-guessing. I recommend in your first version you don't add the complexity of buying vowels or anything like that. 

This is approved but please answer those questions -- I'll keep 👀 on this issue for your response.

**Comment by jmendez50** [comment] 2016-04-28 01:28
Well the score is $100, $200, $300, $400, $500, $600, $700, $800, and Bust. It wont be a wheel that spins and makes sound, but instead it will be just picked from random in the background and will be shown to the player The instructions are easy to add ill just have it print them so they know what to do.

**Comment by halfaro1** [comment] 2016-04-28 21:17
@jmendez50 great! I'll keep my comments on the open pull request.

**Comment by halfaro1** [comment] 2016-04-29 22:29
@jmendez50 I have graded this proposal and project. As a result, I'm closing this. You can see your grade in Blackboard. I hope you have a fantastic summer break :sunny:

**Closed by halfaro1** 2016-04-29 22:29 UTC
Labels: approved, grade updated on blackboard
